from tkinter import *
import random
def action():
    f=random.choice(namevalue.get())
    i=random.choice(namevalue.get())
    r=random.choice(namevalue.get())
    s=random.choice(namevalue.get())
    t=random.choice(namevalue.get())
    s=random.choice(addressvalue.get())
    e=random.choice(addressvalue.get())
    c=random.choice(phonevalue.get())
    o=random.choice(phonevalue.get())
    n=random.choice(Gendervalue.get())
    ID=random.choice(phonevalue.get())
    ID1=namevalue.get()
    password=f+i+r+s+t+s+e+c+o+n
    print("You have Login Succesfully")
    print(f"ID={ID1+"@"+ID}")
    print(f"Password={password}")
root=Tk()
root.geometry('500x500')
root.minsize(250,250)
root.maxsize(500,500)
a=Label(root,text="Welcome To Login Form")
a.grid(row=0,column=2)
name=Label(root,text="Username")
address=Label(root,text="Address")
Phone=Label(root,text="Phone")
Gender=Label(root,text="Gender")
check=Label(root,text="I confirm to terms and condition")
name.grid(row=2,column=0)
address.grid(row=3,column=0)
Phone.grid(row=4,column=0)
Gender.grid(row=5,column=0)
check.grid(row=6,column=2)

namevalue=StringVar()
addressvalue=StringVar()
phonevalue=StringVar()
Gendervalue=StringVar()
checkboxvalue=IntVar()

nameentry=Entry(root,textvariable=namevalue)
addressentry=Entry(root,textvariable=addressvalue)
phoneentry=Entry(root,textvariable=phonevalue)
genderentry=Entry(root,textvariable=Gendervalue)
nameentry.grid(row=2,column=2)
addressentry.grid(row=3,column=2)
phoneentry.grid(row=4,column=2)
genderentry.grid(row=5,column=2)

checkentry=Checkbutton(root,takefocus=checkboxvalue)
checkentry.grid(row=6,column=1)

submit=Button(root,text="SUBMIT",bg="black",fg="white",command=action)
submit.grid(row=7,column=2)
root.mainloop()